name: inmo_test_helpers
description: Test helpers and steps for Inmo Mobile app
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.7.2 < 4.0.0'
  flutter: '3.32.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  patrol: ^3.15.1
  patrol_finders: ^2.7.2
  mockito: ^5.4.6
  get_it: ^8.0.3
  bloc_test: ^10.0.0
  go_router: ^15.1.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.2
  google_sign_in: ^7.1.0
  inmo_mobile:
    path: ../../
  inmo_test_utils:
    path: ../inmo_test_utils

dev_dependencies:
  build_runner: ^2.4.15
  sqflite_common_ffi: ^2.3.5
  bdd_widget_test: ^1.8.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  leak_tracker_flutter_testing: ^3.0.9
  retrofit_generator: ^9.1.9
  http_mock_adapter: ^0.6.1