name: 🔀 Auto-merge

on:
    pull_request_review:
        types:
            - submitted
            
    pull_request_target:
        types:
            - opened
            - synchronize
            - reopened
            - edited
            - labeled
            - unlabeled
            - ready_for_review

    check_suite:
        types:
            - completed

jobs:
    automerge:
        name: 🔀 Auto merge
        runs-on: ubuntu-latest
        steps:
            - name: 🔀 Merge Pull Request
              uses: reitermarkus/automerge@v2.8.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                merge-method: squash
